package com.ar.exception;

public class ExampleThrow {
    public static void main(String[] args) {
    /*    try {
            throw new ArithmeticException("Divison by zero..");
        } catch (ArthimaticException ex) {
            System.out.println(ex.getMessage());
        }*/
    }
}
